Numpy


Numpy is a fundamental libray for scientific computing in python , It provides support for arrays and matrices along with a collection of mathematicl functions to operate on these data structures.

In [ ]:
import numpy as np

In [4]:
## create arrays 

## 1D array

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# reshape the array in the 2D
arr1=np.array([1,2,3,4,5])
arr1.reshape((1,5)) #1 row 5 column

array([[1, 2, 3, 4, 5]])

In [7]:
arr1.shape

(5,)

In [ ]:
### 2D array

arr2=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
(2, 6)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
## ones array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## zero array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
## Identiy\ty matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#### Numpy Vectorised Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])


#### Element wise addition
print("Addition: ",arr1+arr2)

#### Element wise substraction 

print("Substraction:",arr2-arr1)


#### Element wise multiplication 

print("Multiplication:",arr2*arr1)

#### Element wise substraction 

print("Dividion:",arr2/arr1)


Addition:  [11 22 33 44 55]
Substraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Dividion: [10. 10. 10. 10. 10.]


In [22]:
### Univsersal Function

arr=np.array([2,3,4,5,6,7,8,9])

### square root
print(np.sqrt(arr))

### EXponential

print(np.exp(arr))

### sine
print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712 3.        ]
[7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866
  0.98935825  0.41211849]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458]


In [24]:
### Array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array: \n",arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
print(arr[0][1])

print(arr[-1][2])

2
11


In [32]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [45]:
print(arr[0:2,2:])


# 0:2 → take rows from index 0 up to 2 (excluding 2)
# 1: → take columns starting from index 1 till the end

[[3 4]
 [7 8]]


In [48]:
print(arr[1:3,1:3])


[[ 6  7]
 [10 11]]


In [49]:
## Moditfy Array Elements


arr[0][0]=100

print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
### Statistical concepts -- Normalization

## to have a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
print("Mean: ",mean)
print("Standard Deviation:",std_dev)

normalized_data=(data-mean)/std_dev
print("Normalised data : ",normalized_data)



Mean:  3.0
Standard Deviation: 1.4142135623730951
Normalised data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [52]:
## Calculate mean median mode


data=np.array([1,2,3,4,5,6,7,8,9,10])

print("Mean: ",np.mean(data))


print("Median:",np.median(data))

print("Standard Deviation:", np.std(data))

print("Variation: ",np.var(data))

Mean:  5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variation:  8.25


In [56]:
### Logical Operation

data=np.array([1,2,3,4,5,6,7,8,9])

data>5




array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
data[data>5]

array([6, 7, 8, 9])

In [60]:
data[(data>=5) & (data<=8)]


array([5, 6, 7, 8])